### ISSUE TITLE
memory leak because the database is corrupted

### ISSUE THREAD

**Issue by fengwei0328** [etcd-io/bbolt#872] opened 2024-12-12 11:14 UTC
The issue occurs when Docker accesses the metadata.db database. The manifestation of the database corruption is the creation of an invalid `pageNode`, 
https://github.com/etcd-io/bbolt/blob/92c7414587095dfe0602f9de9c76ad8a9489518e/cursor.go#L172-L185

where the flags are 16 instead of the `leafPage` value of 0x02, resulting in continuous creation of invalid `pageNodes`.
I provided a detailed explanation in Moby:
https://github.com/moby/moby/issues/49074

I tried to add a new leafPage to c.stack. First, I checked p.flags. If the value is 16, which is an invalid value, I do not add it and simply break out of the loop. This way, it directly causes a panic and throws an error up the call stack

```go
		p, n := c.bucket.pageNode(pgid)
		if p.flags == 16 {
			break
		}
		c.stack = append(c.stack, elemRef{page: p, node: n, index: 0})
```

**Comment by ahrtr** [comment] 2024-12-13 14:45
Thanks for reporting the issue. The db file is somehow corrupted.

The steps to fix the corrupted db file:

```
$ ./bbolt surgery clear-page-elements --pageId 9 --from-index 3 --to-index 4 --output ./new.db ~/tmp/etcd/bbolt/metadata.db
Please consider executing `./bbolt surgery freelist abandon ...`
All elements in [3, 4) in page 9 were cleared

$ ./bbolt surgery freelist abandon --output ./new2.db ./new.db  
The freelist was abandoned in both meta pages.
It may cause some delay on next startup because bbolt needs to scan the whole db to reconstruct the free list.

$ ./bbolt check ./new2.db 
OK
```

The final `new2.db` should work, please feel free to rename it to `metadata.db`.

The root cause isn't super clear yet. It might be due to mistakenly reusing a non-free page. We will try refactor the freelist management and improve the test coverage in next major release. Refer to https://github.com/etcd-io/bbolt/issues/789

**Comment by fengwei0328** [comment] 2024-12-14 01:57
> Thanks for reporting the issue. The db file is somehow corrupted.
> 
> The steps to fix the corrupted db file:
> 
> ```
> $ ./bbolt surgery clear-page-elements --pageId 9 --from-index 3 --to-index 4 --output ./new.db ~/tmp/etcd/bbolt/metadata.db
> Please consider executing `./bbolt surgery freelist abandon ...`
> All elements in [3, 4) in page 9 were cleared
> 
> $ ./bbolt surgery freelist abandon --output ./new2.db ./new.db  
> The freelist was abandoned in both meta pages.
> It may cause some delay on next startup because bbolt needs to scan the whole db to reconstruct the free list.
> 
> $ ./bbolt check ./new2.db 
> OK
> ```
> 
> The final `new2.db` should work, please feel free to rename it to `metadata.db`.
> 
> The root cause isn't super clear yet. It might be due to mistakenly reusing a non-free page. We will try refactor the freelist management and improve the test coverage in next major release. Refer to #789

I feel that your response helped me successfully fix the metadata.db. I will continue to monitor the root cause moving forward.

**Comment by ahrtr** [comment] 2024-12-14 08:17
> If it's another corrupted database, how do I determine the pageId and index range?

We have several surgery commands, we may need to use different command for different case. Unfortunately, it needs some expertise on bbolt to figure out how to fix the corrupted db file. 

https://github.com/etcd-io/bbolt/blob/92c7414587095dfe0602f9de9c76ad8a9489518e/cmd/bbolt/command_surgery.go#L26-L31

Also not every corrupted db file is guaranteed to be fixed by the surgery commands, just like a doctor cannot guarantee to cure every patient.

**Closed** 2024-12-17 06:44 UTC
