### ISSUE TITLE
SEGV during `(*Tx).rollback`

### ISSUE THREAD

**Issue by tmm1** [etcd-io/bbolt#188] opened 2019-11-07 22:57 UTC
```
unexpected fault address 0x2ab91044
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2ab91044 pc=0x3209d8]

goroutine 7365 [running]:
runtime.throw(0xd9fe37, 0x5)
	runtime/panic.go:774 +0x5c fp=0x59d3a38 sp=0x59d3a24 pc=0x42374
runtime.sigpanic()
	runtime/signal_unix.go:401 +0x310 fp=0x59d3a50 sp=0x59d3a38 pc=0x5928c
github.com/etcd-io/bbolt.(*DB).meta(0x3d8cc80, 0x721)
	github.com/etcd-io/bbolt@v1.3.3/db.go:901 +0x1c fp=0x59d3a6c sp=0x59d3a54 pc=0x3209d8
github.com/etcd-io/bbolt.(*DB).hasSyncedFreelist(...)
	github.com/etcd-io/bbolt@v1.3.3/db.go:323
github.com/etcd-io/bbolt.(*Tx).rollback(0x51e4b00)
	github.com/etcd-io/bbolt@v1.3.3/tx.go:279 +0x68 fp=0x59d3a84 sp=0x59d3a6c pc=0x329ea8
github.com/etcd-io/bbolt.(*Tx).Commit(0x51e4b00, 0x3c63b88, 0x2)
	github.com/etcd-io/bbolt@v1.3.3/tx.go:161 +0x430 fp=0x59d3b24 sp=0x59d3a84 pc=0x3298d8
github.com/blevesearch/bleve/index/scorch.(*Scorch).persistSnapshotDirect(0x3ca1c00, 0x3cc36e0, 0x0, 0x0)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/persister.go:580 +0xfa0 fp=0x59d3de4 sp=0x59d3b24 pc=0x705e1c
github.com/blevesearch/bleve/index/scorch.(*Scorch).persistSnapshot(0x3ca1c00, 0x3cc36e0, 0x416d790, 0x3ed8, 0x1ac5760)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/persister.go:349 +0x74 fp=0x59d3dfc sp=0x59d3de4 pc=0x7045f8
github.com/blevesearch/bleve/index/scorch.(*Scorch).persisterLoop(0x3ca1c00)
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/persister.go:141 +0x6f8 fp=0x59d3fe4 sp=0x59d3dfc pc=0x703440
runtime.goexit()
	runtime/asm_arm.s:868 +0x4 fp=0x59d3fe4 sp=0x59d3fe4 pc=0x747a8
created by github.com/blevesearch/bleve/index/scorch.(*Scorch).Open
	github.com/blevesearch/bleve@v0.8.2-0.20191010234049-157461a2aeb6/index/scorch/scorch.go:170 +0xc8
```

I believe this happened during low memory pressure on the device.

**Comment by houlahaj** [comment] 2020-02-10 21:07
We just hit the same error. Seems there was already an issue opened [here](https://github.com/etcd-io/bbolt/issues/194) for this which was closed because there was no code that could reproduce it. Are you able to reliably reproduce this?

**Comment by ahrtr** [comment] 2023-01-13 07:54
Fixed in https://github.com/etcd-io/bbolt/pull/362. 

Please anyone let me know if you still see the panic.

**Closed by ahrtr** 2023-01-13 07:54 UTC
