### ISSUE TITLE
[Question] Are node methods called with a null node.bucket.bucket outside of unit tests?

### ISSUE THREAD

**Issue by pixelrazor** [etcd-io/bbolt#162] opened 2019-06-18 19:20 UTC
Are there situations where node methods are called with a nil node.bucket.bucket? I didn't run into issues when trying to test a feature, but it broke unit tests since they never initialize the embedded bucket object. I'm debating whether it would fit best to just init the inner bucket struct in the unit tests or add some checks to the node methods to accommodate my feature.
EDIT: for further clarity, if it's just the unit tests, I'll change those. My assumption was that it wasn't necessary to populate that for the original node unit tests, and that it should be expected to be present during normal operation. If that's not the case, and is perfectly fine for that to be null during regular usage, I'll change my implementation to check for and handle a nil *bucket accordingly

**Comment by cenkalti** [comment] 2023-05-16 18:25
Closing as the issue is quite old and not active. Please feel free to reply and re-open if needed.

**Closed by cenkalti** 2023-05-16 18:25 UTC
Labels: question
